erica_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  # head yaw ---------------------------------------
  head_yaw_joint_position:
    type: effort_controllers/JointPositionController
    joint: head_yaw_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # head pitch ---------------------------------------
  head_pitch_joint_position:
    type: effort_controllers/JointPositionController
    joint: head_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # head roll ---------------------------------------
  head_roll_joint_position:
    type: effort_controllers/JointPositionController
    joint: head_roll_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}


  # left arm ---------------------------------------
  l_arm_sh_p_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_arm_sh_r_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_r
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_arm_sh_y_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_sh_y
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_arm_el_p_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_el_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_arm_wr_p_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_wr_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_arm_wr_r_position:
    type: effort_controllers/JointPositionController
    joint: l_arm_wr_r
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # right arm ---------------------------------------
  r_arm_sh_p_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_arm_sh_r_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_r
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_arm_sh_y_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_sh_y
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_arm_el_p_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_el_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_arm_wr_p_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_wr_p
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_arm_wr_r_position:
    type: effort_controllers/JointPositionController
    joint: r_arm_wr_r
    pid: {p: 7500.0, i: 0.1, d: 100.0}


