<?xml version="1.0"?>

<robot name="erica_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="pi" value="3.14159" />
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find erica_description)/urdf/erica_gazebo.gazebo" />
  <xacro:include filename="$(find erica_description)/urdf/materials.xacro" />
  
  <xacro:property name="base_width" value="0.26" />   <!-- 14.5 in -->
  <xacro:property name="base_length" value="0.312" />  <!-- 21 5/8 in -->
  <xacro:property name="base_height" value="0.105" />   <!-- 2.5 in  -->
  <xacro:property name="wheel_radius" value="0.1016" /> <!-- 4.0 in  -->
  <xacro:property name="wheel_width" value="0.0762" />  <!-- 3.0 in  -->
  <xacro:property name="wheel_gap" value="0.0508" />    <!-- 2.0 in  -->
  <xacro:property name="wheel_setback" value="0.041275" />    <!-- 1 5/8 in  -->

  <!-- Used for fixing robot -->


  <!-- main -->
  <link name="body_main">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://erica_description/meshes/asm_don_big_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://erica_description/meshes/asm_don_big_main.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.05 0 0.25" rpy="0 0 0"/>
    <parent link="body_main"/>
    <child link="hokuyo_link"/>
  </joint>

    <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <link name="fl_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="20" />
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <link name="fr_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="20" />
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <link name="bl_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="20" />
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <link name="br_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="20" />
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  
  <joint name="fl_joint" type="fixed">
    <parent link="body_main"/>
    <child link="fl_link"/>
    <origin rpy="0 0 0" xyz="${base_length/2 - wheel_setback} ${base_width/2 + wheel_gap} 0.0"/>
    <axis xyz="0 0 0"/>
    <!-- <dynamics damping="1.0" friction="0.0" spring_stiffness="1" /> -->
  </joint>

  <joint name="fr_joint" type="fixed">
    <parent link="body_main"/>
    <child link="fr_link"/>
    <origin rpy="0 0 0" xyz="${base_length/2 - wheel_setback} ${-base_width/2 - wheel_gap} 0.0"/>
    <axis xyz="0 0 0"/>
    <!-- <dynamics damping="1.0" friction="0.0" spring_stiffness="1" /> -->
  </joint>

  <joint name="bl_joint" type="fixed">
    <parent link="body_main"/>
    <child link="bl_link"/>
    <origin rpy="0 0 0" xyz="${-base_length/2 + wheel_setback} ${base_width/2 + wheel_gap} 0.0"/>
    <axis xyz="0 0 0"/>
    <!-- <dynamics damping="1.0" friction="0.0" spring_stiffness="1" /> -->
  </joint>

  <joint name="br_joint" type="fixed">
    <parent link="body_main"/>
    <child link="br_link"/>
    <origin rpy="0 0 0" xyz="${-base_length/2 + wheel_setback} ${-base_width/2 - wheel_gap} 0.0"/>
    <axis xyz="0 0 0"/>
    <!-- <dynamics damping="1.0" friction="0.0" spring_stiffness="1" /> -->
  </joint>
  
  

  <!-- neck-->
  <joint name="neck_fixed_joint" type="fixed">
    <origin xyz="0 0 0.933" rpy="0 0 0"/>
    <parent link="body_main"/>
    <child link="neck_link"/>
  </joint>

  <link name="neck_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_neck.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_neck.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>
  
<!-- head_yaw -->

  <joint name="head_yaw" type="revolute">
    <origin xyz="0 0 0.164" rpy="0 0 0"/>
    <parent link="neck_link"/>
    <child link="head_yaw_link"/>
    <axis xyz="0 0 1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

<transmission name="head_yaw_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="head_yaw">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="head_yaw_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

 <link name="head_yaw_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_yaw.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_yaw.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- head_pitch -->
  <joint name="head_pitch" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="head_yaw_link"/>
    <child link="head_pitch_link"/>
    <axis xyz="0 -1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="head_pitch_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="head_pitch">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="head_pitch_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="head_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_pitch.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_pitch.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- head_roll -->
  <joint name="head_roll" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="head_pitch_link"/>
    <child link="head_roll_link"/>
    <axis xyz="1 0 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="head_roll_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="head_roll">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="head_roll_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="head_roll_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_roll.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_head_roll.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>



  <!-- head(zed) -->
  <joint name="camera_joint" type="fixed">
    <parent link="head_roll_link"/>
    <child link="zed_camera_center"/>
    <origin xyz="0.0778 0 0" rpy="0 0 0"/>
  </joint>
  
  <!-- Camera Center -->
  <link name="zed_camera_center">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_zed.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_main_zed.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>


  <!-- Left Camera -->
  <joint name="zed_left_camera_joint" type="fixed">
   <parent link="zed_camera_center"/>
   <child link="zed_left_camera_frame"/>
   <origin xyz="0 0.06 0" rpy="0 0 0" />
  </joint>

  <link name="zed_left_camera_frame" />


  <joint name="zed_left_camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57079632679 0.0 -1.57079632679"/>
    <parent link="zed_left_camera_frame"/>
    <child link="zed_left_camera_optical_frame"/>
  </joint>

  <link name="zed_left_camera_optical_frame"/>

  <!-- Right Camera -->
  <joint name="zed_right_camera_joint" type="fixed">
    <parent link="zed_camera_center"/>
    <child link="zed_right_camera_frame"/>
    <origin xyz="0 -0.06 0" rpy="0 0 0" />
  </joint>

  <link name="zed_right_camera_frame" />


  <joint name="zed_right_camera_optical_joint" type="fixed">
   <origin xyz="0 0 0" rpy="-1.57079632679 0.0 -1.57079632679"/>
   <parent link="zed_right_camera_frame"/>
   <child link="zed_right_camera_optical_frame"/>
  </joint>

  <link name="zed_right_camera_optical_frame"/>




  <!-- left_arm -->
  <!-- left_arm_pitch -->
  <joint name="l_arm_sh_p" type="revolute">
    <parent link="body_main"/>
    <child link="l_arm_shoulder_pitch_link"/>
    <origin xyz="0 0.113 0.897" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_sh_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_sh_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_sh_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_shoulder_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- left_arm_roll -->
  <joint name="l_arm_sh_r" type="revolute">
    <parent link="l_arm_shoulder_pitch_link"/>
    <child link="l_arm_shoulder_roll_link"/>
    <origin xyz="0 0.097 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_sh_r_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_sh_r">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_sh_r_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_shoulder_roll_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- left_arm_yaw -->
  <joint name="l_arm_sh_y" type="revolute">
    <parent link="l_arm_shoulder_roll_link"/>
    <child link="l_arm_shoulder_yaw_link"/>
    <origin xyz="0.047 0 0" rpy="0 0 0"/>
    <axis xyz="-1 0 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_sh_y_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_sh_y">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_sh_y_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_shoulder_yaw_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>
  
  <!-- left_arm_elbow -->
  <joint name="l_arm_el_p" type="revolute">
    <parent link="l_arm_shoulder_yaw_link"/>
    <child link="l_arm_elbow_pitch_link"/>
    <origin xyz="0.153 0 0" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_el_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_el_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_el_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_elbow_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- left_arm_wrist_pitch -->
  <joint name="l_arm_wr_p" type="revolute">
    <parent link="l_arm_elbow_pitch_link"/>
    <child link="l_arm_wrist_pitch_link"/>
    <origin xyz="0.2 0 0" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_wr_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_wr_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_wr_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_wrist_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-5.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-5.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- left_arm_wrist_roll -->
  <joint name="l_arm_wr_r" type="revolute">
    <parent link="l_arm_wrist_pitch_link"/>
    <child link="l_arm_wrist_roll_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="l_arm_wr_r_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="l_arm_wr_r">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="l_arm_wr_r_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="l_arm_wrist_roll_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-6.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_l-6.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>



  <!-- right_arm -->
  <!-- right_arm_pitch -->
  <joint name="r_arm_sh_p" type="revolute">
    <parent link="body_main"/>
    <child link="r_arm_shoulder_pitch_link"/>
    <origin xyz="0 -0.113 0.897" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_sh_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_sh_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_sh_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_shoulder_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- right_arm_roll -->
  <joint name="r_arm_sh_r" type="revolute">
    <parent link="r_arm_shoulder_pitch_link"/>
    <child link="r_arm_shoulder_roll_link"/>
    <origin xyz="0 -0.097 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_sh_r_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_sh_r">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_sh_r_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_shoulder_roll_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- right_arm_yaw -->
  <joint name="r_arm_sh_y" type="revolute">
    <parent link="r_arm_shoulder_roll_link"/>
    <child link="r_arm_shoulder_yaw_link"/>
    <origin xyz="0.047 0 0" rpy="0 0 0"/>
    <axis xyz="-1 0 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_sh_y_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_sh_y">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_sh_y_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_shoulder_yaw_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>
  <!-- right_arm_elbow -->

  <joint name="r_arm_el_p" type="revolute">
    <parent link="r_arm_shoulder_yaw_link"/>
    <child link="r_arm_elbow_pitch_link"/>
    <origin xyz="0.153 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_el_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_el_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_el_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_elbow_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

  <!-- right_arm_wrist_pitch -->
  <joint name="r_arm_wr_p" type="revolute">
    <parent link="r_arm_elbow_pitch_link"/>
    <child link="r_arm_wrist_pitch_link"/>
    <origin xyz="0.2 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_wr_p_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_wr_p">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_wr_p_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_wrist_pitch_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-5.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-5.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

<!-- right_arm_wrist_roll -->

  <joint name="r_arm_wr_r" type="revolute">
    <parent link="r_arm_wrist_pitch_link"/>
    <child link="r_arm_wrist_roll_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi}" upper="${pi}" />
    <dynamics damping = "0.7"/>
  </joint>

  <transmission name="r_arm_wr_r_tran">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="r_arm_wr_r">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="r_arm_wr_r_motor">
       <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

  <link name="r_arm_wrist_roll_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-6.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://erica_description/meshes/asm_don_big_arm_r-6.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />      
    </inertial>
  </link>

</robot>



